[project]
name = "pystruct"
version = "0.1.0"
description = "Add a short description here"
authors = ["Toni Kukurin <tkukurin@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
matplotlib = ">=3.8.4,<3.9"

[pypi-dependencies]
package_with_extras = { path = ".", editable = true }
